### ISSUE TITLE
[Request] Open Source Beacon Network Frontend UI

### ISSUE THREAD

**Issue by susheel** [ga4gh-beacon/specification#100]
Request: Open Source Beacon Network Frontend UI

Would it be possible to extract/create a new repo for just the UI frontend of beacon-network? We would like to use it as a reference implementation to inject Bioschemas mentioned in #98

**Comment by mbaudis** [comment]
+1

In the long run, it may be good to have a better separation between beacon-network and Beacon. Also, could provide a Beacon UI...
