### ISSUE TITLE
Update test suite to OpenAPI

### ISSUE THREAD

**Issue by mcupak** [ga4gh-beacon/specification#103]
The tests run on pull requests don't test protobuf and need to be updated.

**Comment by susheel** [comment]
Investigate if [core repo](https://github.com/ga4gh/ga4gh-schemas) test suite for Avro could be migrated to protobuf.

**Comment by susheel** [comment]
@vl62 - Update the schema validation. Most of the installation and testing complete. Fiddly errors to deal with still
