### ISSUE TITLE
Create a build file for specification

### ISSUE THREAD

**Issue by sdelatorrep** [ga4gh-beacon/specification#113]
Create a build configuration so the whole project with its dependencies is compiled.

This is a sub-task of #22

**Comment by sdelatorrep** [comment]
Since the project already has a pom.xml file, the most reasonable solution seemed to take advantage of it and include the missing dependencies: CC and ADA-M. But these projects are not in the Maven Central repository so, AFAIK, they can't be added as dependencies in the pom. 

I suggest downloading/cloning these repositories into the same directory where the beacon folder is. Then they can be included in the compilation and all necessary Java classes are created and, therefore, everything compiles.

I had to look for a different plugin for the proto-to-Java conversion because with the former one I was unable to specify the other proto files required for the correct compilation. I found this one https://github.com/os72/protoc-jar-maven-plugin which was very easy to make it work.

This is what I changed in the pom.xml:
```
    <plugin>
        <groupId>com.github.os72</groupId>
        <artifactId>protoc-jar-maven-plugin</artifactId>
        <version>3.4.0.1</version>
        <executions>
            <execution>
                <phase>generate-sources</phase>
                <goals>
                    <goal>run</goal>
                </goals>
                <configuration>
                    <protocArtifact>com.google.protobuf:protoc:3.0.0</protocArtifact>
                    <includeStdTypes>true</includeStdTypes>
                    <includeDirectories>
                        <include>../ga4gh-consent-policy/src/main/proto</include>
                        <include>../ADA-M</include>
                    </includeDirectories>
                    <inputDirectories>
                        <include>../ga4gh-consent-policy/src/main/proto</include>
                        <include>../ADA-M</include>
                        <include>src/main/proto</include>
                    </inputDirectories>
                    <outputTargets>
                        <outputTarget>
                            <type>java</type>
                        </outputTarget>
                    </outputTargets>
                </configuration>
            </execution>
        </executions>
    </plugin>
```
The rest of the faile remains unchanged.

The tech team requested to add this to the existing PR #110 but I believe it would be better to create a new one for this specific task (and closing issue #22 and merging #110 once and for all). But I do not have any strong feeling for this so I'd like to know what you think.

Please, provide feedback ASAP because this issue and #22 (including PR  #110) will be closed and merged in two weeks if there is no objection.

Thanks!

**Comment by sdelatorrep** [comment]
I had to add the following lines to the ADAM.proto file in order to get rid of compilation errors in the generated Java classes:
```
option java_package = "adam";
option java_multiple_files = true;
```
In fact, just the first line is necessary. The second one just makes it easier (IMHO) to understand the structure and the code as it divides it into different classes.

**Comment by sdelatorrep** [comment]
New PR #115 created.
Please, provide feedback.

**Comment by david4096** [comment]
Any luck with this? I think that without the protobuf you'll want to offer something like swagger-codegen. 

Related https://github.com/ga4gh/data-object-service-schemas/issues/46

**Comment by jrambla** [comment]
This issue seems no longer required as was meant for protobuf
