### ISSUE TITLE
Upgrade to OpenAPI v3.0

### ISSUE THREAD

**Issue by sdelatorrep** [ga4gh-beacon/specification#121]
The current version of the specification conforms with OpenAPI v2.0. Consider upgrading to v3.0.

**Comment by david4096** [comment]
Let me know if you have a good toolchain for this! I believe that the current protobuf > openapi2 stage needs to have an openapi2 > openapi3 conversion.

https://github.com/mermade/swagger2openapi

We would also like to support http://smart-api.info/ that adds a few fields to OpenAPI 3.

**Comment by sdelatorrep** [comment]
@mcupak, I upgraded some months ago the CC and ADAM specs:
* [CC](https://github.com/sdelatorrep/ga4gh-consent-policy/blob/openapi_v3.0.1/consent_code.yaml)
* [ADA-M](https://github.com/sdelatorrep/ADA-M/blob/openapi_v3.0.1/adam.yaml)
