### ISSUE TITLE
BeaconAlleleRequest.referenceName enum

### ISSUE THREAD

**Issue by bwalsh** [ga4gh-beacon/specification#128]
Hi. Using 

```https://app.swaggerhub.com/apiproxy/schema/file/ELIXIR-Finland/ga-4_gh_beacon_api_specification/0.4.0/swagger.yaml```

This [BeaconAlleleRequest.referenceName enum](https://github.com/ga4gh/beacon-team/blob/develop/openapi.yaml#L38) is producing an exception when using it to configure an app using [connexion](https://github.com/zalando/connexion)

curl -X GET --header 'Accept: application/json' 'http://localhost:8080/v1/beacon/query?referenceName=1&start=1&startMin=1&startMax=1&end=1&endMin=1&endMax=1&referenceBases=A&alternateBases=T&assemblyId=GRCh37'
{
  "detail": "u'1' is not one of [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 'X', 'Y']\n\nFailed validating 'enum' in schema:\n    {'description': 'Reference name (chromosome). Accepting values 1-22, X, Y.',\n     'enum': [1,\n              2,\n              3,\n              4,\n              5,\n              6,\n              7,\n              8,\n              9,\n              10,\n              11,\n              12,\n              13,\n              14,\n              15,\n              16,\n              17,\n              18,\n              19,\n              20,\n              21,\n              22,\n              'X',\n              'Y'],\n     'in': 'query',\n     'name': 'referenceName',\n     'type': 'string'}\n\nOn instance:\n    u'1'",
  "status": 400,
  "title": "Bad Request",
  "type": "about:blank"
}

Resolved locally by typing each value in the enum:

#### as-is
```
          enum: 
            - 1
            - 2
            - 3
            - 4
            - 5
            - 6
            - 7
            - 8
            - 9
            - 10
            - 11
            - 12
            - 13
            - 14
            - 15
            - 16
            - 17
            - 18
            - 19
            - 20
            - 21
            - 22
            - X 
            - Y
```
#### to-be

```
          enum: 
            - '1'
            - '2'
            - '3'
            - '4'
            - '5'
            - '6'
            - '7'
            - '8'
            - '9'
            - '10'
            - '11'
            - '12'
            - '13'
            - '14'
            - '15'
            - '16'
            - '17'
            - '18'
            - '19'
            - '20'
            - '21'
            - '22'
            - 'X'
            - 'Y'

```

**Comment by mbaudis** [comment]
@bwalsh @juhtornr Looks like a bug in the YAML parser; some of them tend to have issues with unquoted strings. So while not required per spec., +1 for quoting.

**Comment by garysaunders** [comment]
@sdelatorrep single quoted strings agreed upon

**Comment by sdelatorrep** [comment]
PR #143 merged
