### ISSUE TITLE
`start` conditional, not required

### ISSUE THREAD

**Issue by mbaudis** [ga4gh-beacon/specification#133]
The `start` parameter has to be conditional and not to be required when `startMin` and `startMax` are being provided.

The obvious solution is to have `start` as an array of 1-2 values, bracketing the start value. If only one is provided, or both are identical, this would be the same as the current, confusing, solution. This had been discussed at the Hinxton Bacon meeting; but not been implemented due to legacy considerations (I guess; this wasn't being communicated).

My proposal, with some emphasis from the GKS work streams, is to put the general `start[]`, `end[]` as feature for an upcoming release, possibly with legacy support for single parameters. The differences are mostly in the definition, not in serialisation.

Until then: Bug fix.

**Comment by sdelatorrep** [comment]
+1 to make it optional

**Comment by sdelatorrep** [comment]
PR #141 merged.
