### ISSUE TITLE
variantType missing in BeaconAlleleRequest

### ISSUE THREAD

**Issue by sdelatorrep** [ga4gh-beacon/specification#134]
This parameter was present in the [protobuf specification](https://github.com/ga4gh-beacon/specification/blob/23165dfb878da2be48e31fc890971bbe76dc443f/src/main/proto/ga4gh/beacon.proto#L74) but went missing in the conversion to OpenAPI. We should recover it. 
It must be optional (either `variantType` or `alternateBases` is required).

**Comment by mbaudis** [comment]
+1

I actually had assumed there was some conscious decision before release to remove it, but didn't overly complain since `alternateBases` can be used ATM... Though if you follow VCF, then `DEL` would be an annotation type `<DEL>` in alternateBases, which is awkward.

**Comment by garysaunders** [comment]
@sdelatorrep @mbaudis 
Update documentation so that ALT bases are only accepted as strings of canonical bases: A, C, T, ); IUPAC ambiguity codes (R = A/G; M = A/C); or N.
It is expected that symbolic ALT alleles (DEL, INS, DUP, INV, CNV, DUP:TANDEM, DEL:ME, INS:ME) will be represented in annotation type.

**Comment by sdelatorrep** [comment]
Are you sure you @mbaudis @garysaunders want to include now the IUPAC ambiguity codes? I mean, AFAIK, currently, you can't query this.
I'm suggesting writing only this in the spec:
```
        - name: alternateBases
          description: |
            The bases that appear instead of the reference bases. Accepted values: [ACGT]* or N.
            Symbolic ALT alleles (DEL, INS, DUP, INV, CNV, DUP:TANDEM, DEL:ME, INS:ME) will be represented in `variantType`.
            Optional: either `alternateBases` or `variantType` is required.
          in: query
          required: false
          type: string
          pattern: '^([ACGT]+|N)$'
```

**Comment by mbaudis** [comment]
+1

Good description.
