### ISSUE TITLE
referenceBases should be string, not ENUM

### ISSUE THREAD

**Issue by mbaudis** [ga4gh-beacon/specification#135]
VCF's `REF` field allows the representation of a genome sequence consisting of one *or more* bases from A,T,C,G,N. This is necessary e.g. for _indel_ representation, where a known sequence has a deletion of one or more bases.

The current Beacon specification only allows to provide a single reference base in the query, therefore missing out on these types. A workaround using the structural `DEL` attribute would be possible, but require interpolation of these variants as "structural" deletions on the backend side.

**Comment by sdelatorrep** [comment]
+1

**Comment by sdelatorrep** [comment]
PR #142 merged.
