### ISSUE TITLE
Review Beacon API Examples Query/Responses in the Documentation/OpenAPI

### ISSUE THREAD

**Issue by susheel** [ga4gh-beacon/specification#138]
- [ ] Create `examples` folder in [specification](https://github.com/ga4gh-beacon/specification) repo
- [ ] Create named folders/prefix for each query/response combo
  - Create `request.json` to represent Beacon API request
  - Create `response.json` to represent Beacon API response
  - Create `env.json` to represent any environment variables (specific Beacon server, credentials, etc) to be used for conformance tests

**Comment by mbaudis** [comment]
This will be edited w/ current tribute names & added to the Wiki:

https://docs.google.com/document/d/1uePLlLMl0FzxZxDrsF9IxsC2nYvZ84029fzUD1ULNWI

**Comment by mcupak** [comment]
Can this be done at the OpenAPI level?

**Comment by susheel** [comment]
The idea was to create a list of example queries for documentation purposes and potentially used by reference implementations for conformance tests.

**Comment by mcupak** [comment]
We should still investigate if we can do this at the OpenAPI level. That would be preferred.

**Comment by mbaudis** [comment]
+1 @mcupak

**Comment by jrambla** [comment]
+1 @mcupak
