### ISSUE TITLE
Change CC reference to official release

### ISSUE THREAD

**Issue by sdelatorrep** [ga4gh-beacon/specification#139]
In the openAPI definition, we are referencing the CC and ADA-M openAPI definitions I did in my personal repo (original definitions are using protobuf), see [this](https://github.com/ga4gh-beacon/specification/blob/03a28806a78bd0dbc296e85ae8fde0e5124529ca/beacon.yaml#L354) and [this](https://github.com/ga4gh-beacon/specification/blob/03a28806a78bd0dbc296e85ae8fde0e5124529ca/beacon.yaml#L366).
I created 2 PR (see [this](https://github.com/ga4gh/ga4gh-consent-policy/pull/11) in CC repo and [this](https://github.com/ga4gh/ADA-M/pull/9) in ADA-M repo) with the conversion but they must be merged into a new branch (e.g. develop-openapi) and change the URLs in the yaml files.

**Comment by mcupak** [comment]
The references should be to tags, not just any branches, so that the implementation cannot change and break things. Before resolving this, we should make releases in CC and ADA-M repos (based on master branches) and refer to them. Francis should be consulted on the ADA-M stuff.

**Comment by sdelatorrep** [comment]
@mcupak , could you do what you just said with the PR in the CC repo? I can't (not enough permissions).

**Comment by FrancisJMR** [comment]
Hi Sabela, Thanks for working on the conversion of ADA-M to OpenAPI. I'm not familiar with the syntax but I'm guessing that you've tested? I'll merge your changes and we can revert if something doesn't work.

**Comment by sdelatorrep** [comment]
Thank you @FrancisJMR! We don't have any test suite or reference implementation yet. Currently, the only thing we can do is checking that there are no syntactic errors with the Swagger editor. 
It would be great if somebody (in beacon team or whoever) can review it and check I didn't do any mistake (e.g. forgot a field).

**Comment by garysaunders** [comment]
https://github.com/ga4gh-beacon/specification/pull/196

**Comment by mcupak** [comment]
I'll reopen this - we're referring to the upstream repositories now, but it would be better to refer to a release rather than a specific commit.

**Comment by sdelatorrep** [comment]
I created a new issue #209 for changing the ADA-M reference (as doing a release in that repo is out of our control).

**Comment by FrancisJMR** [comment]
Hi @sdelatorrep -- do you need us to merge the code into a master release? @mcupak are there any active repos for ADA-M you are working on that should be merged?

**Comment by sdelatorrep** [comment]
Hi @FrancisJMR , yes, that would be great! This way, we can reference a release (tag) instead of a specific commit.

**Comment by antbro** [comment]
HI Guys

Francis is leading on ADA-M repo.

I have asked him to comment yesterday, and assume he will do so presently

Regards
Tony


________________________________________

**Comment by FrancisJMR** [comment]
@mcupak I've created a merge request to master -- please review and confirm if all else is good. thanks!

**Comment by sdelatorrep** [comment]
I've just did a release in the CC repository so the Beacon spec can now point to it.
