### ISSUE TITLE
Point to official repository in references

### ISSUE THREAD

**Issue by sdelatorrep** [ga4gh-beacon/specification#140]
This:
```
$ref: 'https://raw.githubusercontent.com/sdelatorrep/beacon-team/openapi_v2.0/beacon.yaml#/definitions/BeaconAlleleResponse'
```
is using my personal repository. It should be:
```
$ref: 'https://raw.githubusercontent.com/ga4gh-beacon/specification/develop-openapi/beacon.yaml#/definitions/BeaconAlleleResponse'
```
Problem: The branch is encoded within the URL. WDYT is the best way to tackle this?

**Comment by sdelatorrep** [comment]
See Miro's comment in #139

**Comment by sdelatorrep** [comment]
IMPORTANT: This issue might not apply anymore if we merge both files into a single one as suggested [here](https://github.com/ga4gh-beacon/specification/issues/150).

**Comment by mcupak** [comment]
Closing in favour of #139 and #150.
