### ISSUE TITLE
Consolidate API versions

### ISSUE THREAD

**Issue by mcupak** [ga4gh-beacon/specification#150]
The API consists of 2 files - `beacon.yaml` and `openapi.yaml`, which contain conflicting versions under `info/version` (1.0.0 vs. 0.4.0).

**Comment by mcupak** [comment]
The files are actually not that large - should we just merge them into a single file to avoid this problem?

**Comment by sdelatorrep** [comment]
We split into 2 files for clarification (paths in a file and definitions in another) but it's totally true that they are not that big (around 600 lines in total). We can consider merging.
