### ISSUE TITLE
Disclaimer support

### ISSUE THREAD

**Issue by mcupak** [ga4gh-beacon/specification#154]
This came up during the discussion of the search API and I thought it could be a good suggestion for beacon. Would it be useful to support a disclaimer/terms of use at the API level?

E.g.:
```
"disclaimer" : {
  	"version": "<semantic version>"
  	"text": "Disclaimer text...",
  	"terms" : "Terms text...",
  }
```

See e.g. [MME disclaimers](https://github.com/ga4gh/mme-apis/tree/master/disclaimers).

**Comment by mbaudis** [comment]
+1; good extension.

However - which level? Dataset? Beacon? Both? Probably the latter - or would this be handled through more structured info (DURI ...)?

**Comment by jrambla** [comment]
I'll vote for both.
But will restrict that to a link to the disclaimer info, not the full text in the answer.

**Comment by jrambla** [comment]
Which would be the reason to make it an specific entry instead of using the "description" or "externalURL" entries? Would a Beacon Network make any use of it or it is irrelevant for them?

**Comment by juhtornr** [comment]
@jrambla is asking the right question. What is the use case for this? How this would be shown in the user interface and is this really different than existing `description`?

**Comment by mbaudis** [comment]
Well, @mcupak had pointed to the [MME disclaimers](https://github.com/ga4gh/mme-apis/tree/master/disclaimers). However, I wouldn't follow up on this in the current form - this should be re-written with specific use case and demonstration/proposal, if needed.

**Comment by mcupak** [comment]
I agree with the above. This came up as a suggestion from MME. I thought it was an interesting idea worth running by the group to see if anyone has a use case. I personally don't have one. If ELIXIR doesn't have one either, let's close this.
