### ISSUE TITLE
Support for mitochondrial DNA

### ISSUE THREAD

**Issue by mcupak** [ga4gh-beacon/specification#155]
Should we support mtDNA? Some beacons use MT as a chromosome identifier, but I'm not sure what the "right" way to do this is.

**Comment by garysaunders** [comment]
We should definitely support MT variants.

"MT" is the correct definition in GRCh37 (GCA_000001405.14 and previous) and GRCh38 (GCA_000001405.15 and later).

**Comment by sdelatorrep** [comment]
PR #212

**Comment by sdelatorrep** [comment]
PR #212 merged.
