### ISSUE TITLE
Incorrect description for updateDateTime

### ISSUE THREAD

**Issue by mcupak** [ga4gh-beacon/specification#166]
The description of the `updateDateTime` property is a copy-past from `createDateTime`.

**Comment by mbaudis** [comment]
I would vote for removing `createDateTime`. It is hard to keep this consistent & meaningful.

**Comment by sdelatorrep** [comment]
PR fixing the description: #185

Please, @mbaudis, create a new issue for discussing removing `createDateTime` field. Thanks!
