### ISSUE TITLE
Remove KeyValuePair

### ISSUE THREAD

**Issue by mcupak** [ga4gh-beacon/specification#168]
`KeyValuePair` should not be used to model pairs. It's only used in arrays, which means it should be replaced with a proper map.

The question is, do we want a map of string-string (consistency with previous versions of the spec), or string-object (not possible to capture in the previous versions of the spec, but ultimately what we wanted, even though potentially harder to with when consuming the API).

**Comment by juhtornr** [comment]
@mcupak is this the way how you would like to resolve this? This is based on:

https://swagger.io/docs/specification/data-models/dictionaries/

**Comment by mcupak** [comment]
That would be the way to do it, assuming string values (and assuming the PR is resubmitted against develop).

It's probably a good idea to do string values for the patch release, and have a new issue for arbitrary objects for 0.5. WDYT?

**Comment by jrambla** [comment]
Why do we want "objects" instead of "strings"?
The original aim of info was to add arbitrary info that the Beacon owner wants to add. Thus, in my understanding, no "object" with a defined schema could be referenced here. Am I missing something?

**Comment by jrambla** [comment]
Closing it as it is addressed in #226
