### ISSUE TITLE
Clarify response for invalid datasets

### ISSUE THREAD

**Issue by mcupak** [ga4gh-beacon/specification#170]
What is the correct response if an invalid dataset ID is specified in the request? What about when the client specifies multiple dataset IDs, one of which is not valid?

**Comment by sdelatorrep** [comment]
What is an invalid ID? An ID which does not follow the pattern? What if you don't have a pattern in your beacon? How can you detect "invalid" IDs? IMHO, the beacon should not care about this. If the user has made a typo it's their problem (the user can check the valid IDs querying the base endpoint, `/`). And, if they ask for the detailed response per dataset, they can see the "wrong" ID does not appear.

**Comment by sdelatorrep** [comment]
I've checked the spec and if there is an error then `exists` should be `null`:
```
    BeaconError:
      description: >-
        Beacon-specific error. This should be non-null in exceptional situations
        only, in which case `exists` has to be null.
```
Considering this and after our conversation in today's technical call, I imagine something like this in the case of a user requesting the detailed response:
```
{
"exists" : "true"
...
"datasetAlleleResponses" : [
    {
    "exists" : null,
    ...
    error : {
       "errorCode" : 404
       "errorMessage" : "Dataset not found"
    },
    {
    "exists": false,
    ...
    },
    {
    "exists": true,
    ...
    }
],
...
"error": null
...
```
(notice there wouldn't be any `error` in the top level)
But, if the user has not requested the detailed response, we cannot provide both `exists` and `error` field at the same time so the schema would be (unless we change the spec, of course):
```
{
"exists" : null
...
"datasetAlleleResponses" : null,
...
"error": {
       "errorCode" : 404
       "errorMessage" : "Dataset not found"
}
...
```
(notice it does not matter if some of the datasets are found in the beacon).

Please, share your thoughts!

**Comment by jrambla** [comment]
IMHO we shouldn't tamper good answers because of tricky use cases. Lets respond with the positive/correct datasets and leave out the "not found" datasets. I need to double check if the HTTP responses allows for something like "warning" or "answer including errors" response codes (not found at a first inspection). In positive, my approach will be to add such warning as a descriptive message detailing "not found" dataset ids.
