### ISSUE TITLE
Extending structural variants with breakends

### ISSUE THREAD

**Issue by mbaudis** [ga4gh-beacon/specification#173]
The current Beacon specification does not provide the option to query translocation partners if those are on a different reference sequence. 
The "breakends" concept in VCF (chapter 5.2, p12ff in VCFv4.2) details the use of the "BND" variant type: 

* standard (CHROM, POS, REF) attributes for the first position 
* INFO::SVTYPE=BND
* the definition of fusion partner (chromosome and position) in the "ALT" attribute
* optional INFO::CIPOS=n,m;CIEND=o,p for bracketing uncertain position ranges

Each such rearrangement is treated as single variant (1 line in VCF), with the inferred combinations of re-arrangements (e.g. reciprocal translocation events, complex recombinations...) being represented through cross-referencing variant ids.

The most awkward handling in VCF is the forcing of the 2nd partner into the "ALT" column, which obviously does not apply here. Also, brackets for start and end positions are in place already.

#### Proposal

I propose to
* add a second an attribute `mateReference` (other christening ideas welcome)
* document different use cases of the "BND" `variantType`
    - classical translocations, e.g. t(8;14)(q24.1;q32) MYC-IGH
    - breaks with unknown partner
    - large inversions
    - ...

**Comment by jrambla** [comment]
@mbaudis Is that still necessary after having mateName added?

**Comment by mbaudis** [comment]
@jrambla This is handled by https://github.com/ga4gh-beacon/specification/pull/176 & could be closed after merging.

**Comment by sdelatorrep** [comment]
Duplicated by #176
