### ISSUE TITLE
Review v0.4.1 - snapshot

### ISSUE THREAD

**Issue by garysaunders** [ga4gh-beacon/specification#178]
We will conduct a full review of the v0.4.1 - snapshot spec prior to release and subsequent submission of spec to GA4GH for product approval.

Issues identified should be described in GitHub tickets and tagged with the [0.4.1 milestone](https://github.com/ga4gh-beacon/specification/milestone/8).

**Comment by juhtornr** [comment]
There is a [Beacon.md](https://github.com/ga4gh-beacon/specification/issues/179) file which describes what is a Beacon API, how it works, etc.

**Comment by garysaunders** [comment]
@saifEBI can this issue be closed?

**Comment by saifEBI** [comment]
Yes,
