### ISSUE TITLE
Add optional contact information to Beacon response metadata

### ISSUE THREAD

**Issue by mfiume** [ga4gh-beacon/specification#180]
Survey from Beacon Network suggests that contacting data owners is an important next action. Should be possible to optionally include phone or email information.

**Comment by antbro** [comment]
+1
Tony

--
  Professor Anthony J Brookes
  Department of Genetics and Genome Biology
  University of Leicester
  University Road
  Leicester, LE1 7RH, UK
  Tel: +44 (0)116 2523401
  Tel: +44 (0)116 2044767
  Mbl: +44 (0)777 0620396
  Fax: +44 (0)116 2523378
  -
  ** Mundum mutatu errore singillatim
  ** http://libraryofmistakes.com/about
  -
  ** Where is the wisdom we have lost in knowledge?
  ** Where is the knowledge we have lost in information?
  ** T.S. Eliot


Marc Fiume wrote:

**Comment by mbaudis** [comment]
+1

... while making sure it is GDPR conform :-/

**Comment by mcupak** [comment]
We already have this at an [organizational level](https://github.com/ga4gh-beacon/specification/blob/develop/beacon.yaml#L479) (supports email/URL). Isn't that enough?
