### ISSUE TITLE
Remove `createDateTime` attribute

### ISSUE THREAD

**Issue by mbaudis** [ga4gh-beacon/specification#186]
As mentioned in the discussion to #166, we could/should `createDateTime` altogether since it is hard to keep this consistent & meaningful.

However, not a strong opinion & other comments required.

**Comment by mcupak** [comment]
Tentatively -1. Why is it difficult to keep it consistent and meaningful?

**Comment by mbaudis** [comment]
@mcupak 

* disagreements about "does it refer to the object or the data" - whereas change implies a modification of the data, at least in a broader consensus
* there are very few instances where the _created_ provides additional information beyond _changed_

Alas, I just wanted to point out that this may not be needed as part of a query schema... Just putting this out for + or -

**Comment by jrambla** [comment]
I'll not remove stuff that is already in previous (and deployed) version, thus breaking retrocompatibility, if we don't have a strong reason for it.
Having said so, we could/should also offer an option to allow for "not available" data.

**Comment by mbaudis** [comment]
Closing this; old comment & settled both in implementatio (fixed original issue) and spirit (most for leaving it in).

**Comment by mbaudis** [comment]
Closing this; old comment & settled both in implementatio (fixed original issue) and spirit (most for leaving it in).
