### ISSUE TITLE
requirements.txt missing

### ISSUE THREAD

**Issue by saifEBI** [ga4gh-beacon/specification#187]
README specifies a requirement file for Python dependencies.  This file is missing from the master branch.

**Comment by sdelatorrep** [comment]
Hi @saifEBI , are you reviewing `master`branch? I think you should use `develop` because all bugs are being fixed there (`master`is outdated and contains things which do not make sense, e.g. `pom.xml` still references protobuf stuff)

**Comment by saifEBI** [comment]
develop is labelled 0.4.1-SNAPSHOT, given I'm supposed to be reviewing 0.4 I though  the master was the stable 0.4 release.

**Comment by sdelatorrep** [comment]
Yes, it is but many things have already been fixed in `develop` (as the one raised in this issue), if you review `master`you will detect these issues again.

**Comment by saifEBI** [comment]
Ah ok, I will switch to the develop branch then.
