### ISSUE TITLE
No error codes on default endpoint: /

### ISSUE THREAD

**Issue by saifEBI** [ga4gh-beacon/specification#188]
Response is only specified for success code 200.

There are no response codes for a client or server failures

**Comment by sdelatorrep** [comment]
I was about to solve this but 1) we are not specifying server failures anywhere in the spec, 2) the client errors we are managing are of 3 types but this endpoint has no parameters (400) and cannot produce an unauthorised or forbidden error (401 or 403) (see [/query](https://github.com/ga4gh-beacon/specification/blob/21d7fed2eb7278649284ef86f3c8b4f81b6917c8/beacon.yaml#L165) endpoint).
I think we can close this. WDYT?

**Comment by saifEBI** [comment]
I agree with this.
