### ISSUE TITLE
What does MISS mean?

### ISSUE THREAD

**Issue by Welliton309** [ga4gh-beacon/specification#207]
I understood that `includeDatasetResponses` values:

- ALL means all datasets even those that don't have the queried variant
- HIT means only datasets that have the queried variant
- MISS means opposite to HIT value, only datasets that don't have the queried variant
- NONE don't return datasets response.

I this right? If yes, there is another question. If `BeaconDatasetAlleleResponse::exists` attribute is *missing* (due to wrong Assembly ID for example, should not be `false`), does it should be treated as MISS?

**Comment by sdelatorrep** [comment]
I think the beacon should not deal with wrong values, this is the user's responsibility. It does not matter if the user provides a wrong assembly ID or an assembly not present in this beacon, it's the same case for this beacon: no match found. If `includeDatasetResponses=HIT`then no dataset will appear in the list; if `includeDatasetResponses=MISS`, all (public) datasets would appear.

**Comment by jrambla** [comment]
If I get the question correctly, I'll say that an error if different from a miss, and using the later as a synonym of the former would be misleading to the user. On the other hand, adding "ERROR" as a filter could be something that will improve clarity and comprehensiveness to the picture.
