### ISSUE TITLE
Add support for mitochondrial variants

### ISSUE THREAD

**Issue by teemukataja** [ga4gh-beacon/specification#220]
Currently the specification allows the following chromosomes: `1-22, X, Y`. Support for mitochondrial variants should be added, e.g. `MT`, as it is an integral part of the human genome.

Mitochondrial variants are also found for example in the [1000genomes project](http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/) and the Beacon Network service (BeaconOfBeacons) also support [this](https://beacon-network.org/#/search?pos=10&chrom=MT&allele=C&ref=T&rs=GRCh37).

**Comment by sdelatorrep** [comment]
Hi @teemukataja . This issue is duplicating an existing one #155. I'm closing this one.
