### ISSUE TITLE
Modify base sequence regex

### ISSUE THREAD

**Issue by teemukataja** [ga4gh-beacon/specification#221]
Currently the specification enforces the following regular expressions to validate base sequences: `^([ACGT]+|N)$` which disallows some more complex usage of wildcards. We propose another approach, with the following regular expression: `^([ACGTN]+)$` which would allow users to find wildcards from within partly known sequences, not only as single nucleotide polymorphisms.

![beaconregex](https://user-images.githubusercontent.com/17040963/46648825-6b958600-cb9f-11e8-988c-21b7ff99ee67.png)
Figure 1. Validation of example base sequences according to current specification (left) and proposed form (right).

**Comment by mbaudis** [comment]
+1 on this, and IMO can go into a point release (no need to wait for major version update).

**Comment by sdelatorrep** [comment]
+1
