### ISSUE TITLE
Error in Beacon Queries page

### ISSUE THREAD

**Issue by Tom-Shorter** [ga4gh-beacon/specification#234]
https://github.com/ga4gh-beacon/specification/wiki/Beacon-Queries#range-queries-and-structural-variants

The first section states the following:

The coordinate system that should be used throughout GA4GH standards is 0-based half open. So in a sequence of

```
ACCGTCGA
```
... the exact match for GTC would be

```
start: 4,
end: 7
```
... due to interbase coordinates.

This should actually state:

The coordinate system that should be used throughout GA4GH standards is 0-based half open. So in a sequence of

```
ACCGTCGA
```
... the exact match for GTC would be

```
start: 3,
end: 6
```
... due to interbase coordinates.

4,7 is 1 based half open  where as 3,6 is 0 based half open.

**Comment by sdelatorrep** [comment]
You are totally right. I'm adding this issue to the next milestone.

**Comment by antbro** [comment]
nice one!
T

________________________________________

**Comment by sdelatorrep** [comment]
Fixed!
