### ISSUE TITLE
Consider using the data models of the core GA4GH APIs (e.g. Variant Annotation, Metadata, etc.)

### ISSUE THREAD

**Issue by mfiume** [ga4gh-beacon/specification#25]

**Comment by skeenan** [comment]
+1

**Comment by mcupak** [comment]
Comments from the Google Doc for reference, so that we have all the info in one place:
```
Miro Cupak (4:24 PM Mar 28): Can this be a feature request for the next version of the API?
Stephen Keenan (7:29 AM Apr 8): @miro: If this schema was being developed on github as per the normal contributing rules I would -1 this suggestion. Really want to prevent splintering and fragmentation here. If the current (Variant Annotation, Metadata etc) schemas are lacking please state what they are and let the developers know so that they can resolve.
Marc Fiume (9:26 AM Apr 8): Yes, Stephen, I think this is the right way forward ultimately. One consideration for us to make is whether the core APIs also capture the right level of information. For example, the GAVariant resource captures variant information (my interpretation is that a variant includes a position but not an allele) and the GACall resource captures an instance of a variant, including the allelic information, but for a specific sample. For Beacon, since the response is allele-centric, we may need a concept of a GAAllele. This may be just a pedantic naming issue, but if we can reuse something similar to GACall (which has map<array<string>> info) as GAAllele then it will already support a superset of functionality as we intend to accomplish here.
```

**Comment by jrambla** [comment]
We suggested to keep this "for later" (until further discussed, actually) just because I don't see it clearly fit in the current phylosophy of Beacon v.0.x...
I.e. If you query for an "allele", how we jump from this simple thing to related "Variant Annotation" or "Metadata"?
My feeling is that this could generate a significant, undetermined, amount of discussion that we don't want to delay the release of other features.
On the contrary, it could be straigthforward (I haven't checked yet).
But, in general, my guess is that it comes after the "Indels".

**Comment by mcupak** [comment]
I share Jordi's concerns regarding this last-minute integration of the core API and would +1 postponing it to the next release, if that's an option.

Having said that, here are some thoughts:

The list of all the records from the core API we could potentially utilize (v0.6.0.a4):
```
$ grep --exclude "*methods*" "^record" *.avdl | sed "s/record//" | sed "s/ {//"

alleleAnnotations.avdl: AnalysisResult
alleleAnnotations.avdl: AlleleLocation
alleleAnnotations.avdl: VariantAnnotationSet
alleleAnnotations.avdl: HGVSAnnotation
alleleAnnotations.avdl: TranscriptEffect
alleleAnnotations.avdl: VariantAnnotation
common.avdl: Position
common.avdl: ExternalIdentifier
common.avdl: CigarUnit
metadata.avdl: OntologyTerm
metadata.avdl: Experiment
metadata.avdl: Dataset
metadata.avdl: Analysis
reads.avdl: Program
reads.avdl: ReadStats
reads.avdl: ReadGroup
reads.avdl: ReadGroupSet
reads.avdl: LinearAlignment
reads.avdl: ReadAlignment
references.avdl: Reference
references.avdl: ReferenceSet
variants.avdl: VariantSetMetadata
variants.avdl: VariantSet
variants.avdl: CallSet
variants.avdl: Call
variants.avdl: Variant
```

Out of those, I think we could include the following as optional fields in `BeaconDatasetAlleleResponse`:
- `Variant`
- `VariantAnnotation`
- maybe a list of `OntologyTerm` associated with the returned variant (applicable/useful?)

...and the following as optional fields in `BeaconDataset`:
- `VariantSet`
- `VariantAnnotationSet`
- maybe a list of `OntologyTerm` associated with the given dataset (applicable/useful?)

`Variant`, `VariantAnnotation` and `VariantAnnotationSet` refer to a `VariantSet`, which basically forces us to incorporate `VariantSet` (which pulls in `Dataset` and `ReferenceSet`) into `BeaconDataset`, probably as a mandatory field replacing some of the current fields we're using. It's quite a disruptive change at this point, hence the concerns expressed at the beginning of this comment.

Thoughts? Any other records we should use?

**Comment by antbro** [comment]
+1

Tony



________________________________

**Comment by mcupak** [comment]
Agreed to postpone to 1.0.

**Comment by kozbo** [comment]
+1

**Comment by jrambla** [comment]
As it is a very old issue and things have moved on, I'm closing this issue and expecting to open new ones as required.
