### ISSUE TITLE
Add the info entry to BeaconAlleleResponse

### ISSUE THREAD

**Issue by jrambla** [ga4gh-beacon/specification#253]
All objects are having an "info" entry, like BeaconDatasetAlleleResponse, but BeaconAlleleResponse is lacking it. I'm suggesting to add it to this object to be consistent.

**Comment by jrambla** [comment]
All objects are having an "info" entry, like BeaconDatasetAlleleResponse, but BeaconAlleleResponse is lacking it. I'm suggesting to add it to this object to be consistent.

**Comment by sdelatorrep** [comment]
I suggest moving this issue to next milestone 1.1.1 so we merge PR #226 before and then, we can use the new format.

**Comment by sdelatorrep** [comment]
PR #257 merged.
