### ISSUE TITLE
Generate documentation from Proto3

### ISSUE THREAD

**Issue by mcupak** [ga4gh-beacon/specification#40]
Add documentation, preferably at least partially autogenerated.

Options to consider:
- Avro/Sphinx (see [ga4gh/schemas](https://github.com/ga4gh/schemas))
- Swagger
- ...

**Comment by mcupak** [comment]
@jrambla Well, partially. See e.g. https://github.com/ga4gh/beacon-team/issues/43#issuecomment-231257028.

My main issue is that we don't have any documentation at this point, and that's a problem for an API. We don't need to create a perfect documentation for 0.4, but we really should have something for the very next release. I'd suggest to mimic what the core API has right now, and think about how to make it better in a future release.

I like Swagger, and in many ways, it would be an ideal documentation tool for beacon. The main issue to figure out here is how to use it without duplicating the contents of our Avro/Protobuf schemas. The recent developments in the core API suggest a way to do it, but it needs some polishing. I'd let them figure it out and see what we can do later. For now, we just need something.

**Comment by kozbo** [comment]
@mcupak @jrambla : We had L-shift write a parser to crawl through the protobuf definitions and scrape out the comments, then process the results into rst files. But since then we have discovered an easier and more maintainable way to do it using annotations. The plan is to add some strings to the schemas and then run the proto files through a swagger conversion. From there it will be easy to generate rst files that include all the comments.

That is the plan, though it may be a bit before we get back to implementing it.

**Comment by david4096** [comment]
I've more or less completed the work for this on the GA4GH schemas. You can see how I annotated the rpc endpoints [here](https://github.com/david4096/schemas/blob/annotated/src/main/proto/ga4gh/reference_service.proto#L38). With one somewhat ugly `protoc` call one can then generate API definitions and documentation for your messages and endpoints.

I added some preliminary documentation to the bottom of https://github.com/david4096/schemas/blob/annotated/INSTALL.rst .

**Comment by jrambla** [comment]
@david4096 could you update us on the status, please?

**Comment by admincbib** [comment]
Working workflow using  Go Programming Language, protobuf and swagger to generate the documentation from a proto3 file.
Files are converted into JSON format with protoc and the HTML documentation is generated with swagger-codegen. Spectacle can be used instead of swagger to create the HTML files.

**Comment by admincbib** [comment]
apidoc (http://apidocjs.com/) does not seem to work with the JSON generated by protoc

**Comment by mcupak** [comment]
Does it work then? If the protobuf->swagger conversion doesn't work well for us, we can also go the route of annotating the reference implementation, which uses the classes compiled from protobuf.

**Comment by admincbib** [comment]
Yes it work
I have generated a HTML documentation using protoc (to convert in JSON) and swagger-codegen
I will send it to you to verify that the documentation seems correct
we can then think of the automation of this procedure

**Comment by susheel** [comment]
@admincbib I missed the attachment. Could you put it somewhere online and attach the link here?
