### ISSUE TITLE
Feature evaluation Beacon for structural and metadata queries and quantitative results (ELIXIR D1.1) 

### ISSUE THREAD

**Issue by juhtornr** [ga4gh-beacon/specification#80]

**Comment by mbaudis** [comment]
The GA4GH schema now allows representation of first structural variant types:

https://github.com/ga4gh/schemas/blob/master/src/main/proto/ga4gh/variants.proto#L196

This should be used as basis for developing the Beacon implementation.

**Comment by heinzstockinger** [comment]
See related pull request and issue:
* https://github.com/ga4gh/beacon-team/pull/65
* https://github.com/ga4gh/beacon-team/issues/20

**Comment by mbaudis** [comment]
Now: https://github.com/ga4gh/beacon-team/pull/94

**Comment by mbaudis** [comment]
An alternative implementation of the DUP + DEL + ranges is presented in #95, which leaves the current `BeaconAlleleRequest` intact.

**Comment by heinzstockinger** [comment]
+1

**Comment by mbaudis** [comment]
@heinzstockinger Is this for the general topic, the image or #95 ?  ;-)

**Comment by heinzstockinger** [comment]
@mbaudis my +1 refers to the topic ... also expressed at #95
