### ISSUE TITLE
(bio)schema.org markup for Beacons and BeaconDatasets on beacon-network.org

### ISSUE THREAD

**Issue by susheel** [ga4gh-beacon/specification#98]
## Feature Request

(bio)schema.org markup for Beacons and BeaconDatasets on beacon-network.org

Specification is at https://drive.google.com/open?id=1kQE3lixvBjBiZ8X3I1Mi44c3dcdgf4SshoGdNX5-_TE

### Desired behaviour

Visiting https://beacon-network.org/#/directory would list the structured data extracted from each [Beacon](https://docs.google.com/document/d/1kQE3lixvBjBiZ8X3I1Mi44c3dcdgf4SshoGdNX5-_TE/edit#heading=h.gjdgxs) and sub-[BeaconDataset](https://docs.google.com/document/d/1kQE3lixvBjBiZ8X3I1Mi44c3dcdgf4SshoGdNX5-_TE/edit#heading=h.ggmtyo1aipo) entry

**Comment by juhtornr** [comment]
Implemented in ELIXIR Beacon reference implementation.
