### ISSUE TITLE
Response should provide a list of all assemblyIds

### ISSUE THREAD

**Issue by mbaudis** [ga4gh-beacon/specification#99]
When informing about a dataset, `assemblyId` should provide a list of all assemblies the dataset's variant collections are mapped to.

**Comment by mcupak** [comment]
Is it unreasonable to expect a dataset to have a single assembly? I.e. create multiple datasets at the beacon level if you have data with different assemblies.

**Comment by jdylan** [comment]
Multiple datasets due to multiple assemblies could cause confusion.

**Comment by mbaudis** [comment]
The logic comes from  considering metadata part of the "dataset". It seems more intuitive to have

* dataset "_some_description_" has data mapping to [`assemblyIds`]

then

* dataset "_same_description_" has data mapping to `assemblyId_1`
* dataset "_same_description_" has data mapping to `assemblyId_2`

Just the question where your primary concern lies (dataset w/ metadata or variant collection).

**Comment by jrambla** [comment]
Sorry, I don't get some of the comments in this issue, thus, excuse me if my comment is not totally in focus.
IMHO, as the request comes with a given assemblyId, we should just provide answers related to the requested assembly. The fact that the assemblyId is in the response is for sanity check. Am I wrong?
